---
- name: Configure Raspberry Pi with CamillaDSP
  hosts: raspi
  become: yes
  
  roles:
    - role: overlay
      tags: [overlay]
      
    - role: test_overlay
      tags: [test_overlay]

    - role: test_speakers
      tags: [test_speakers]

    - role: camilladsp
      tags: [camilladsp]
    
    - role: config
      tags: [config]
    
    - role: volume
      tags: [volume]
    
    - role: readonly
      tags: [readonly]