---
- name: Configure Raspberry Pi with CamillaDSP
  hosts: raspi
  become: yes
  vars_files:
    - vars.yml
  
  roles:
    - role: overlay
      tags: [overlay]
      
    - role: test_overlay
      tags: [test_overlay]

    - role: test_speakers
      tags: [test_speakers]

    - role: camilladsp
      tags: [camilladsp]
    
    - role: config
      tags: [config]
      when: config_source_dir | length > 0
      
    - role: volume
      tags: [volume]
      when: volume_control_enabled | bool