---
# Default installation directory for CamillaDSP
camilladsp_install_dir: "/home/{{ camilladsp_user }}/camilladsp"

# User and group that will own the CamillaDSP installation
camilladsp_user: "michsos"
camilladsp_group: "michsos"

# CamillaDSP version to install
camilladsp_version: "3.0.2"

# Python version to use (this will be used by the script if needed)
camilladsp_python_version: "3"

# Note: The GUI uses port 5005 by default