---
# Tasks for testing all audio channels
# Only runs when test_audio_channels is set to true

- name: Ensure alsa-utils is installed
  apt:
    name: alsa-utils
    state: present
    update_cache: true
  become: true
  when: test_audio_channels | bool

- name: Get number of channels from device
  shell: arecord -D hw:GenericStereoAu,0 --dump-hw-params /dev/null 2>&1 | grep CHANNELS | awk '{print $3}' | sed 's/\[//' | sed 's/\]//' | awk -F ' ' '{print $2}'
  register: max_channels
  ignore_errors: true
  become: true
  when: test_audio_channels | bool

- name: Display number of channels
  debug:
    msg: "Device supports up to {{ max_channels.stdout }} channels"
  when: test_audio_channels | bool and max_channels.stdout is defined

- name: Test each channel with speaker-test
  shell: "speaker-test -D hw:GenericStereoAu,0 -c {{ max_channels.stdout }} -t sine -f 1000 -l 1 -r {{ item }}"
  with_sequence: start=1 end="{{ max_channels.stdout|int }}"
  register: speaker_test_results
  ignore_errors: true
  become: true
  when: test_audio_channels | bool and max_channels.stdout is defined and max_channels.stdout|int > 0

- name: Display speaker test results
  debug:
    msg: "Channel {{ item.item }} test completed with return code {{ item.rc }}"
  with_items: "{{ speaker_test_results.results }}"
  when: test_audio_channels | bool and speaker_test_results.results is defined

- name: Test all channels simultaneously
  shell: "speaker-test -D hw:GenericStereoAu,0 -c {{ max_channels.stdout }} -t sine -f 1000 -l 1"
  register: all_channels_test
  ignore_errors: true
  become: true
  when: test_audio_channels | bool and max_channels.stdout is defined and max_channels.stdout|int > 0

- name: Display all channels test result
  debug:
    msg: "All channels test completed with return code {{ all_channels_test.rc }}"
  when: test_audio_channels | bool and all_channels_test is defined